# Generated by Django 5.1 on 2024-09-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_mymodel_description_mymodel_email_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MyModel",
        ),
    ]
